sonar.projectKey=SignSpeak-Team_signspeak-backend
sonar.organization=signspeak-team
sonar.branch.name=main

sonar.projectName=signspeak-backend
sonar.projectVersion=1.0

sonar.sources=services
sonar.tests=tests
sonar.python.version=3.11

# Exclusiones globales (no aparecen en SonarCloud)
sonar.exclusions=**/__pycache__/**, **/*.pyc, terraform/**, scripts/**, docs/**, infrastructure/**, .github/**, **/*.md, **/*.json, signspeak-frontend-web/**

# Exclusiones de Cobertura (aparecen pero no afectan al %)
sonar.coverage.exclusions=tests/**, services/*/dev/**, services/*/demos/**, services/**/__init__.py, services/*/src/api/models/**

sonar.python.coverage.reportPaths=coverage.xml