sonar.projectKey=SignSpeak-Team_signspeak-backend
sonar.organization=signspeak-team
sonar.projectName=SignSpeak Backend
sonar.sources=services
sonar.tests=tests
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**,terraform/**,scripts/**
sonar.python.coverage.reportPaths=coverage.xml